version: '3.8'
services:
  movies:
    image: veerperu1712/paytmmovies:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3
  train:
    image: veerperu1712/paytmtrain:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3
  dth:
    image: veerperu1712/paytmdth:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
  recharge:
    image: veerperu1712/paytmrecharge:latest
    ports:
      - "94:80"
    deploy:
      replicas: 3
